### basic settings

title: Phyloinformatics Lab
description: We apply computational intelligence, phylogenetics, and bioinformatics to make sense of multi-omics data and answer practical questions in One Health.
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: /machadodj

# site social media and other links
links:
  email: dmachado@uncc.edu
  google-scholar: Denis Jacob Machado
  github: machadodj
  twitter: machadodj_bio
  instagram: phyloinformatics
  youtube: channel/UCThn5Dman-FTCUWzvz8s9KQ

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
