##
# 2025
##

# 2025: ML
- id: doi:10.1111/cla.12610
  title: Machine learning models accurately predict clades of proteocephalidean tapeworms (Onchoproteocephalidea) based on host and biogeographical data
  publisher: Cladistics
  date: "2025-03-06"
  image: images/20250206_cla12610fig2m.jpg
  tags:
    - ai
    - phylogenetics
    - biogeography
    - parasitology
  authors:
  - Alvesa, P. V.
  - da Silva, R. J.
  - Scholzc, T.
  - de Chambrier, A.
  - Duchenko, A.
  - Machadob, D. J.

##
# 2024
##

# 2024: MCT
- id: doi:10.1186/s12864-024-10926-7
  title: Unveiling putative modulators of mutable collagenous tissue in the brittle star Ophiomastix wendtii - an RNA-Seq analysis
  publisher: BMC Genomics
  date: "2024-10-29"
  image: images/20241029_mct.jpg
  tags:
    - echinoderms
    - collagen
    - transcriptomics
  authors:
  - Reyhaneh Nouri
  - Vladimir Mashanov
  - April Harris
  - Gari New
  - William Taylor
  - Daniel Janies
  - Robert W. Reid
  - Denis Jacob Machado

# 2024: ZIKV
- id: doi:10.3390/cells13171491
  title: The Relationship between HERV, Interleukin, and Transcription Factor Expression in ZIKV Infected versus Uninfected Trophoblastic Cells
  publisher: Cells
  date: "2024-09-05"
  image: images/20240402_ZIKV.jpg
  tags:
    - flaviviruses
    - viruses
    - transcriptomics
    - infection
  authors:
  - Anderson Luís da Costa
  - Paula Prieto-Oliveira
  - Márcia Duarte-Barbosa
  - Robert Andreata-Santos
  - Cristina M. Peter
  - Thamires Prolo
  - Fernando Antoneli
  - Maria Isabel V. G. de Carvalho
  - Ricardo Durães-Carvalho
  - Marcelo Ribeiro da Silva Briones
  - Juliana T. Maricato
  - Paolo M. A. Zanotto
  - Denis Jacob Machado
  - Luiz Mario Ramos Janini
  # link: https://doi.org/10.3390/cells13171491

# 2024: SARS-CoV-2
- id: doi:10.3389/fviro.2024.1419276
  title: Predicting Antibody and ACE2 Affinity for SARS-CoV-2 BA.2.86 and JN.1 with In Silico Protein Modeling and Docking
  publisher: Frontiers in Virology
  date: "2024-07-18"
  image: images/yasa_etal_2024.jpg
  tags:
    - coronavirus
    - docking
    - epidemiology
  authors:
  - Shirish Yasa
  - Sayal Guirales-Medrano
  - Denis Jacob Machado
  - Colby T. Ford
  - Daniel A. Janies

##
# 2023
##

# 2023: Editorial: Phylogenetics in the one health context
#- id: doi:10.3389/fmicb.2023.1307616
# title: Phylogenetics in the One Health context
# publisher: Frontiers in Microbiology
# date: "2023-10-26"
# image: images/OneHealth.png
# tags:
#   - phylogenetics
#   - One Health
# authors:
#   - Denis Jacob Machado
#   - Larry Jiménez-Ferbans
#   - Kary Ocaña
#   - Adriano de Bernardi Schneider
# link: https://phyloinformatics.com/2023/10/26/Editorial.html

# 2023: Editorial: Phylogenetics in the one health context
- id: issn:2508-7436
  title: Replicating Ford et al.’s investigation on the immune consequences and SARS-CoV-2 antibody’s binding affinity using an in silico approach
  publisher: ICICPE 2023
  date: "2023-12-29"
  image: images/ICICPE2023.png
  tags:
    - artificial intelligence
    - genomic epidemiology
    - molecular docking
    - viruses
  authors:
  - Cameron Jones
  - Hannah Zeru
  - Denis Jacob Machado
#link: http://icicpe.org/wp-content/uploads/2023/12/ICICPE-2023_vol.71.pdf

# 2023: Echinoderm radial glia in adult cell renewal, indeterminate growth, and regeneration
- id: doi:10.3389/fncir.2023.1258370
  image: https://www.frontiersin.org/files/Articles/1258370/fncir-17-1258370-HTML/image_m/fncir-17-1258370-g002.jpg
  tags:
    - echinoderms
    - non-model organism
    - invertebrates
    - zoology

# 2023: Predictions of the SARS-CoV-2 XBB.1.5 variant
- id: doi:10.3389/fviro.2023.1172027
  image: https://upload.wikimedia.org/wikipedia/commons/8/82/SARS-CoV-2_without_background.png
  tags:
    - artificial intelligence
    - genomic epidemiology
    - molecular docking
    - phylogenetics
    - sensitivity analyses
    - viruses
    - zoonoses

##
# 2022
##

# 2022: EchinoDB
- id: doi:10.1186/s12863-022-01090-6
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12863-022-01090-6/MediaObjects/12863_2022_1090_Fig1_HTML.png?as=webp
  tags:
    - echinoderms
    - non-model organism
    - genomics
    - invertebates
    - zoology
    - database
    - softare

# 2022: Twinkle twinkle brittle star
- id: doi:10.1186/s12864-022-08750-y
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12864-022-08750-y/MediaObjects/12864_2022_8750_Fig1_HTML.png?as=webp
  tags:
    - echinoderms
    - non-model organism
    - genomics
    - invertebates
    - zoology
    - gene annotation
    - gene prediction
    - mitogenome
    - nuclear genome

# 2022: Indeterminate growth in brittle stars
- id: doi:10.1186/s12983-022-00461-0
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12983-022-00461-0/MediaObjects/12983_2022_461_Fig2_HTML.png?as=webp
  tags:
    - echinoderms
    - gene expression
    - invertebrates
    - non-model organism
    - regeneration
    - zoology

# 2022: Predictions of the SARS-CoV-2 Omicron variant
- id: doi:10.3389/fviro.2022.830202
  image: https://www.frontiersin.org/files/Articles/830202/fviro-02-830202-HTML/image_m/fviro-02-830202-g005.jpg
  tags:
    - artificial intelligence
    - genomic epidemiology
    - molecular docking
    - phylogenetics
    - sensitivity analyses
    - viruses
    - zoonoses

##
# 2021
##


# 2021: Fundamentals of genomic epidemiology
- id: doi:10.1017/ash.2021.222
  image: https://static.cambridge.org/binary/version/id/urn:cambridge.org:id:binary:20211202193237344-0196:S2732494X21002229:S2732494X21002229_fig1.png?pub-status=live
  tags:
    - coronavirus
    - genomic epidemiology
    - high-throughput sequencing
    - One Health
    - viruses
    - zoonoses


# 2021: Fundamental evolution of all CoVs
- id: doi:10.1111/cla.12454
  image: https://static.cambridge.org/binary/version/id/urn:cambridge.org:id:binary:20211202193237344-0196:S2732494X21002229:S2732494X21002229_fig3.png?pub-status=live
  title: Fundamental evolution of all Orthocoronavirinae including three deadly lineages descendent from Chiroptera-hosted coronaviruses - SARS-CoV, MERS-CoV and SARS-CoV-2
  tags:
    - character categorization
    - coronaviruses
    - gene annotation
    - gene prediction
    - genomic epidemiology
    - outgroup selection
    - phylogenetics
    - sequence alignment
    - sensitivity analyses
    - viruses
    - zoonoses

# 2021: Support
- id: doi:10.1111/cla.12496
  image: https://onlinelibrary.wiley.com/cms/asset/3a5d0667-7501-4f3d-bdde-6e1914fcb4a4/cla12496-fig-0001-m.jpg
  authors:
    - Denis Jacob Machado
    - Fernando Portella de Luna Marques
    - Larry Jiménez-Ferbans
    - Taran Grant
  tags:
    - phylogenetics
    - clade support
    - clade frequencies
    - sensitivity analyses
    - maximum likelihood
    - software

# 2021: Evidence of absence treated as absence of evidence
- id: doi:10.1016/j.ympev.2020.106966
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1055790320302384-gr5.jpg
  tags:
    - phylogenetics
    - clade support
    - clade frequencies
    - sequence alignment
    - sensitivity analyses
    - maximum likelihood

# 2021: The phylogeny of Dendropsophini
- id: doi:10.1111/cla.12429
  image: https://onlinelibrary.wiley.com/cms/asset/bae01dd2-0f27-45c1-b5b3-896c7ddd460e/cla12429-fig-0003-m.jpg
  tags:
    - amphibians
    - character categorization
    - outgroup selection
    - phylogenetics
    - vertebrates
    - wildcard taxa
    - zoological taxonomy
    - zoology


# 2021: Comparative characterization of mitogenomes
- id: doi:10.3389/fgene.2021.788871
  image: https://www.frontiersin.org/files/Articles/788871/fgene-12-788871-HTML/image_m/fgene-12-788871-g003.jpg
  tags:
    - comparative genomics
    - gene annotation
    - gene prediction
    - genome skimming
    - invertebates
    - mitogenome
    - parasitology
    - zoology

##
# 2020
##


# 2020: FLAVi
- id: doi:10.3390/v12080892
  image: https://www.mdpi.com/viruses/viruses-12-00892/article_deploy/html/images/viruses-12-00892-g009-550.jpg
  tags:
    - character categorization
    - flaviviruses
    - gene annotation
    - gene prediction
    - genomic epidemiology
    - outgroup selection
    - phylogenetics
    - sequence alignment
    - sensitivity analyses
    - viruses
    - zoonoses
    - software


# 2020: Active Notch signaling
- id: doi:10.1371/journal.pone.0232981
  image: https://journals.plos.org/plosone/article/figure/image?size=large&id=10.1371/journal.pone.0232981.g003
  tags:
    - echinoderms
    - gene expression
    - invertebrates
    - non-model organism
    - regeneration
    - zoology

# 2020: The first complete mitochondrial genome of the sand dollar
- id: doi:10.1016/j.ygeno.2019.10.007
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0888754319301855-gr1.jpg
  tags:
    - echinoderms
    - genome skimming
    - invertebrates
    - mitogenome
    - non-model organism
    - zoology

##
# 2019
##


# 2019: Genome skimming
- id: doi:10.7717/peerj.7543
  image: https://dfzljdn9uc3pi.cloudfront.net/2019/7543/1/fig-2-2x.jpg
  tags:
    - genome skimming
    - invertebrates
    - mitogenome
    - non-model organism
    - zoology


##
# 2018
##


# 2018: A new strategy to infer circularity
- id: doi:10.1002/ece3.3918
  image: https://onlinelibrary.wiley.com/cms/asset/e7a780bc-056a-4cb7-bd7c-2e8c1c554289/ece33918-fig-0001-m.jpg
  tags:
    - amphibian
    - genome skimming
    - vertebrates
    - mitogenome
    - non-model organism
    - sensitivity analyses
    - zoology
    - software

##
# 2017
##


# 2017: Phylogenetic Systematics of Dart-Poison Frogs and Their Relatives
- id: doi:10.2994/SAJH-D-17-00017.1
  image: https://bioone.org/ContentImages/Journals/sajh/12/s1/SAJH-D-17-00017.1/graphic/f36_S1.jpg
  tags:
    - amphibians
    - character categorization
    - outgroup selection
    - phylogenetics
    - vertebrates
    - zoological taxonomy
    - zoology

##
# 2016
##


# 2016: Mitogenome assembly from genomic multiplex libraries
- id: doi:10.1111/1755-0998.12492
  image: https://onlinelibrary.wiley.com/cms/asset/4febcad6-6a17-4f0b-9b24-d97882b9f346/men12492-fig-0001-m.jpg
  tags:
    - amphibian
    - genome skimming
    - vertebrates
    - mitogenome
    - non-model organism
    - zoology
    - software
##
# 2015
##


# 2015: YBYRÁ
- id: doi:10.1186/s12859-015-0642-9
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12859-015-0642-9/MediaObjects/12859_2015_642_Fig1_HTML.gif?as=webp
  tags:
    - character categorization
    - phylogenetics
    - sensitivity analyses
    - topological distances
    - tree comparison
    - wildcard taxa
    - software


##
# 2012
##


# 2012: The forgotten origin of \emph{Acanthobothrium} Blanchard, 1848 (Tetraphyllidea: Onchobothriidae)
# - title: The forgotten origin of Acanthobothrium Blanchard, 1848 (Tetraphyllidea: Onchobothriidae)
#   authors:
#     - Denis Jacob Machado
#     - Fernando Portella de Luna Marques
#   publisher: Zootaxa
#   date: 2012
#   link: https://www.biotaxa.org/Zootaxa/article/view/zootaxa.3505.1.7
- id: doi:10.11646/zootaxa.3505.1.7
  image: https://uconn-today-universityofconn.netdna-ssl.com/wp-content/uploads/2017/12/2_20171029-Acanth_rodm.jpg
  tags:
    - invertebates
    - parasitology
    - zoological taxonomy
    - zoology
    